source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

abstract_target 'iOS' do
    platform :ios, '9.0'

    target 'BasicTunnelExtension-iOS' do
        pod 'PIATunnel', :path => '..'
    end
    target 'BasicTunnel-iOS' do
    end
end

abstract_target 'macOS' do
    platform :osx, '10.11'

    target 'BasicTunnelExtension-macOS' do
        pod 'PIATunnel', :path => '..'
    end
    target 'BasicTunnel-macOS' do
    end
end
